### ISSUE TITLE
Update to 0.8.0

### ISSUE THREAD

**Issue by bvogelzang** [jarofghosts/ractive-browserify#1]
Can we get this updated to the latest version of 0.8.0? It would be much appreciated. Thanks!

**Comment by jarofghosts** [comment]
I'm working on it right now, the issue being that they never updated `rcu` which is what I was previously using to parse. I think I have it working, but want to run some more tests to make sure.

**Comment by jarofghosts** [comment]
If you'd like, there is a `ractive-0.8` branch I've just pushed that you are welcome to try to see if it works for you. If it does, I will gladly publish it ASAP.

**Comment by jarofghosts** [comment]
published `ractive-browserify@0.8.0`
